services:
  postgres-test:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

  redis-test:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - test_redis_data:/data

volumes:
  test_postgres_data:
  test_redis_data:
